// Loads the REAL shipping share/qe_database.json (generated by
// tools/import_qe_research.py from research/qe_database_research.json)
// through the real nukex::QEDatabase loader, as opposed to the synthetic
// fixtures used by test_qe_database.cpp. Proves the generated data against
// the actual consumer, catching schema drift between the importer (Task 15)
// and the loader (Task 3).
#include "catch_amalgamated.hpp"
#include "nukex/calibration/qe_database.hpp"

#include <filesystem>

using namespace nukex;
namespace fs = std::filesystem;

static fs::path shipped_db_path() {
    return fs::path(NUKEX_SHARE_DIR) / "qe_database.json";
}

TEST_CASE("QEDatabase: shipping DB loads and parses", "[qe_database][shipping]") {
    QEDatabase db;
    auto result = db.load_shipped(shipped_db_path().string());
    REQUIRE(result.ok);

    // Sanity bounds from tools/import_qe_research.py's transform of
    // research/qe_database_research.json (~55 cameras, ~87 filters).
    REQUIRE(db.n_cameras() >= 50);
    REQUIRE(db.n_filters() >= 80);
}

TEST_CASE("QEDatabase: shipping DB — known cameras resolve", "[qe_database][shipping]") {
    QEDatabase db;
    REQUIRE(db.load_shipped(shipped_db_path().string()).ok);

    // Verified present via: python3 -c "import json;
    // print('asi1600mm' in json.load(open('share/qe_database.json'))['cameras'])"
    REQUIRE(db.has_camera("asi1600mm"));
    REQUIRE(db.has_camera("asi071mc"));
    REQUIRE_FALSE(db.has_camera("DoesNotExist"));
}

TEST_CASE("QEDatabase: shipping DB — known filters resolve", "[qe_database][shipping]") {
    QEDatabase db;
    REQUIRE(db.load_shipped(shipped_db_path().string()).ok);

    // Verified present via: python3 -c "import json;
    // print(list(json.load(open('share/qe_database.json'))['filters'].keys())[:10])"
    REQUIRE(db.has_filter("Antlia-Ha-3nm-Pro"));
    REQUIRE(db.has_filter("Antlia-OIII-3nm-Pro"));
    REQUIRE_FALSE(db.has_filter("DoesNotExist"));
}
