// Loads the REAL shipping share/qe_database.json (generated by
// tools/import_qe_research.py from research/qe_database_research.json)
// through the real nukex::QEDatabase loader, as opposed to the synthetic
// fixtures used by test_qe_database.cpp. Proves the generated data against
// the actual consumer, catching schema drift between the importer (Task 15)
// and the loader (Task 3).
#include "catch_amalgamated.hpp"
#include "nukex/calibration/qe_database.hpp"

#include <filesystem>
#include <fstream>
#include <sstream>

using namespace nukex;
namespace fs = std::filesystem;

static fs::path shipped_db_path() {
    return fs::path(NUKEX_SHARE_DIR) / "qe_database.json";
}

TEST_CASE("QEDatabase: shipping DB loads and parses", "[qe_database][shipping]") {
    QEDatabase db;
    auto result = db.load_shipped(shipped_db_path().string());
    REQUIRE(result.ok);

    // Sanity bounds from tools/import_qe_research.py's transform of
    // research/qe_database_research.json (~55 cameras, ~87 filters).
    REQUIRE(db.n_cameras() >= 50);
    REQUIRE(db.n_filters() >= 80);
}

TEST_CASE("QEDatabase: shipping DB — known cameras resolve", "[qe_database][shipping]") {
    QEDatabase db;
    REQUIRE(db.load_shipped(shipped_db_path().string()).ok);

    // Verified present via: python3 -c "import json;
    // print('asi1600mm' in json.load(open('share/qe_database.json'))['cameras'])"
    REQUIRE(db.has_camera("asi1600mm"));
    REQUIRE(db.has_camera("asi071mc"));
    REQUIRE_FALSE(db.has_camera("DoesNotExist"));
}

TEST_CASE("QEDatabase: shipping DB — known filters resolve", "[qe_database][shipping]") {
    QEDatabase db;
    REQUIRE(db.load_shipped(shipped_db_path().string()).ok);

    // Verified present via: python3 -c "import json;
    // print(list(json.load(open('share/qe_database.json'))['filters'].keys())[:10])"
    REQUIRE(db.has_filter("Antlia-Ha-3nm-Pro"));
    REQUIRE(db.has_filter("Antlia-OIII-3nm-Pro"));
    REQUIRE_FALSE(db.has_filter("DoesNotExist"));
}

// The production path: the QE database compiled into the module binary must
// load with NO file present and regardless of the process working directory.
// This is the exact scenario that broke on end-user installs (bare relative
// "share/qe_database.json" resolved against an unpredictable CWD).
TEST_CASE("QEDatabase: embedded DB loads independent of file/CWD", "[qe_database][embedded]") {
    QEDatabase db;
    auto result = db.load_embedded();
    REQUIRE(result.ok);
    REQUIRE(db.n_cameras() >= 50);
    REQUIRE(db.n_filters() >= 80);
    // The user's camera (ASI2400MC dual-NB OSC) must resolve from the built-in DB.
    REQUIRE(db.has_camera("asi2400mc"));
    REQUIRE(db.has_filter("Antlia-Ha-3nm-Pro"));
}

// Guards the codegen: the bytes compiled in must be byte-identical to the
// on-disk source, so the shipping binary can never drift from share/qe_database.json.
TEST_CASE("QEDatabase: embedded JSON is byte-identical to on-disk source", "[qe_database][embedded]") {
    std::ifstream f(shipped_db_path().string(), std::ios::binary);
    REQUIRE(f.is_open());
    std::stringstream ss;
    ss << f.rdbuf();
    REQUIRE(embedded_qe_database_json() == ss.str());
}
