# Embeds a file as a C++ byte array so the QE database ships INSIDE the module
# binary — no loose file, no runtime path lookup, no CWD dependency.
#
# Invoked at build time via:  cmake -DQE_JSON_IN=<in> -DQE_CPP_OUT=<out> -P embed_qe_database.cmake
#
# HEX embedding (not a raw string literal) is deliberate: it cannot be broken by
# any byte sequence in the JSON (e.g. a stray )json" delimiter, NULs, or non-UTF8).
file(READ "${QE_JSON_IN}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _n "${_hexlen} / 2")
# "ab12.." -> "0xab,0x12,.."
string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")

file(WRITE "${QE_CPP_OUT}"
"// AUTO-GENERATED by embed_qe_database.cmake from share/qe_database.json.
// DO NOT EDIT — regenerated on every build when the JSON changes.
#include \"nukex/calibration/qe_database.hpp\"

#include <string>

namespace nukex {

static const unsigned char kEmbeddedQeDbBytes[] = { ${_bytes} };

std::string embedded_qe_database_json() {
    return std::string(reinterpret_cast<const char*>(kEmbeddedQeDbBytes), ${_n});
}

} // namespace nukex
")
