#ifndef PICopilotVersion_h
#define PICopilotVersion_h

#define PICOPILOT_MODULE_VERSION_MAJOR     0
#define PICOPILOT_MODULE_VERSION_MINOR     1
#define PICOPILOT_MODULE_VERSION_REVISION  0
#define PICOPILOT_MODULE_VERSION_BUILD     4

#define PICOPILOT_STR_(x)  #x
#define PICOPILOT_STR(x)   PICOPILOT_STR_(x)

#define PICOPILOT_VERSION_STRING \
    PICOPILOT_STR(PICOPILOT_MODULE_VERSION_MAJOR) "." \
    PICOPILOT_STR(PICOPILOT_MODULE_VERSION_MINOR) "." \
    PICOPILOT_STR(PICOPILOT_MODULE_VERSION_REVISION) "." \
    PICOPILOT_STR(PICOPILOT_MODULE_VERSION_BUILD)

#endif
